/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function js_main(): void;
export function __wbg_resourceswrapper_free(a: number): void;
export function resourceswrapper_new(): number;
export function resourceswrapper_set_debug_font_data(a: number, b: number, c: number): void;
export function resourceswrapper_set_pixel_font_data(a: number, b: number, c: number): void;
export function resourceswrapper_set_sprites(a: number, b: number): void;
export function resourceswrapper_set_sprites_metadata(a: number, b: number, c: number): void;
export function resourceswrapper_set_noise(a: number, b: number): void;
export function resourceswrapper_set_aesthetic_shader(a: number, b: number, c: number): void;
export function resourceswrapper_set_menu_shader(a: number, b: number, c: number): void;
export function resourceswrapper_set_vignette_shader(a: number, b: number, c: number): void;
export function resourceswrapper_set_map_obscuring_shader(a: number, b: number, c: number): void;
export function resourceswrapper_set_grayscale_shader(a: number, b: number, c: number): void;
export function resourceswrapper_set_agent_smith_laugh(a: number, b: number): void;
export function resourceswrapper_set_last_level_drone(a: number, b: number): void;
export function resourceswrapper_set_level_finish(a: number, b: number): void;
export function resourceswrapper_set_quote(a: number, b: number): void;
export function resourceswrapper_set_music(a: number, b: number): void;
export function __wbg_wrapper_free(a: number): void;
export function wrapper_new(a: number, b: number, c: number): number;
export function wrapper_step(a: number, b: number): void;
export function wrapper_handle_resize(a: number): void;
export function wrapper_handle_key_down(a: number, b: number): void;
export function wrapper_handle_key_up(a: number, b: number): void;
export function wrapper_handle_mouse_down(a: number, b: number): void;
export function wrapper_handle_mouse_up(a: number, b: number): void;
export function wrapper_handle_mouse_move(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_start(): void;
